[package]
name = "forkjoin-benchmarking"
version = "0.1.0"
authors = ["Linus Färnstrand <faern@faern.net>"]

[dependencies]
argparse = "*"
forkjoin = "2.*"

[dependencies.criterion]
git = "https://github.com/faern/criterion.rs"
# path = "../criterion/criterion.rs/"
branch = "filestat"

# [dependencies.forkjoin]
# path = "../forkjoin.v2/"

# [profile.release]
# lto = true
