[package]
name = "criterion-forkjoin"
version = "0.1.0"
authors = ["Linus Färnstrand <faern@faern.net>"]

[dependencies.criterion]
# git = "https://github.com/japaric/criterion.rs"
path = "../criterion.rs/"

[dependencies.forkjoin]
path = "../forkjoin/"
